//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetApi.Models
{
    using Microsoft.EntityFrameworkCore;

    public partial class BudgetApiEntities : DbContext
    {
        public BudgetApiEntities(DbContextOptions<BudgetApiEntities> options) : base(options)
        {
        }
    
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Budget>().ToTable("Budget");
            modelBuilder.Entity<BudgetType>().ToTable("BudgetType");
            modelBuilder.Entity<GiftCard>().ToTable("GiftCard");
            modelBuilder.Entity<Income>().ToTable("Income");
            modelBuilder.Entity<IncomeSource>().ToTable("IncomeSource");
            modelBuilder.Entity<Purchase>().ToTable("Purchases");
        }
    
        public virtual DbSet<Budget> Budgets { get; set; }
        public virtual DbSet<BudgetType> BudgetTypes { get; set; }
        public virtual DbSet<GiftCard> GiftCards { get; set; }
        public virtual DbSet<Income> Incomes { get; set; }
        public virtual DbSet<IncomeSource> IncomeSources { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
    }
}
