//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetApi.Models
{
    using BudgetApi.Shared;
    using Microsoft.EntityFrameworkCore;

    public partial class BudgetEntities : DbContext
    {
        public BudgetEntities(DbContextOptions<BudgetEntities> options) : base(options)
        {
        }
    
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BudgetEntity>().ToTable("Budget");
            modelBuilder.Entity<BudgetTypeEntity>().ToTable("BudgetType");
            modelBuilder.Entity<GiftCardEntity>().ToTable("GiftCard");
            modelBuilder.Entity<IncomeEntity>().ToTable("Income");
            modelBuilder.Entity<IncomeSourceEntity>().ToTable("IncomeSource");
            modelBuilder.Entity<PurchaseEntity>().ToTable("Purchases");
            modelBuilder.Entity<CustomSettingsEntity>().ToTable("Settings");
        }
    
        public virtual DbSet<BudgetEntity> Budgets { get; set; }
        public virtual DbSet<BudgetTypeEntity> BudgetTypes { get; set; }
        public virtual DbSet<GiftCardEntity> GiftCards { get; set; }
        public virtual DbSet<IncomeEntity> Incomes { get; set; }
        public virtual DbSet<IncomeSourceEntity> IncomeSources { get; set; }
        public virtual DbSet<PurchaseEntity> Purchases { get; set; }
        public virtual DbSet<CustomSettingsEntity> Settings { get; set; }
    }
}
