//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget.DB;

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

public partial class ReceiptRecordGroupEntity
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ReceiptRecordGroupEntity()
    {
        //this.Incomes = new HashSet<IncomeEntity>();
    }

    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid ReceiptRecordId { get; set; }
    public int BudgetTypeId { get; set; }
    public decimal Amount { get; set; }

    //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    //public virtual ICollection<IncomeEntity> Incomes { get; set; }
    [ForeignKey("ReceiptRecordId")]
    public virtual ReceiptRecordEntity IncomeSource { get; set; }

    [ForeignKey("BudgetTypeId")]
    public virtual BudgetTypeEntity BudgetType { get; set; }
}
