//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCard
    {
        public int Id { get; set; }
        public string Place { get; set; }
        public decimal InitialAmount { get; set; }
        public string CardNumber { get; set; }
        public string AccessCode { get; set; }
    }
}
