//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public int Id { get; set; }
        public int SourceId { get; set; }
        public string SourceDetails { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsReimbursement { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public bool IsCash { get; set; }
    
        public virtual IncomeSource IncomeSource { get; set; }
    }
}
