//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseEntity
    {
        public int Id { get; set; }
        public int BudgetingGroupId { get; set; }
        public int PurchaseTypeId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public string PaymentType { get; set; }
        public int? GiftCardId { get; set; }
        public System.DateTime Date { get; set; }
        public Guid? ReceiptRecordGroupId { get; set; }
        public bool FutureReimbursement { get; set; }
    }
}
